apiVersion: v1
kind: Pod
metadata:
  name: my-aws-cli
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<ACCOUNT_NAME>:role/<ROLE_NAME>
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: [sh, -c, "sleep 1000"]