apiVersion: v1
kind: Pod
metadata:
  name: my-aws-proxy
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<ACCOUNT_NAME>:role/<ROLE_NAME>
spec:
  containers:
  - name: aws-proxy
    image: alpine/socat:1.0.5
    args:
    - tcp-listen:80,fork,reuseaddr
    - tcp-connect:169.254.169.254:80